void troca(int a[], int x,int y);
void bubbleSort(int a[],int n);
void insertSort(int vetor[],int size);
void selectionSort(int vetor[], int size);
void mergeSort(int v[],int p,int q);
void merge(int v[],int p, int meio, int q);
void quickSort(int *v, int inicio, int fim);
int particiona (int*v, int inicio, int fim);
void troca2(int *a, int *b);
void insertion_sort(int *inicio, int *fim);
void heapify(int *dados, int tamanho, int pai);
void heap_sort(int *base, int tamanho);
int* particiona2(int *inicio, int *fim);
void introsort_recursivo(int *inicio, int *fim, int profundidade);
void introsort(int *vetor, int tamanho);
int mediana(int *a, int *b, int *c);